spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.31.117:3306/gulimall_ums?userUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: mall-member

mybatis-plus:
  mapper-locations: classums_ath*:/mapper/**/*.xml  #classpath*:/  引用得依赖classpath都寻找
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto    #auto increase

server:
  port: 8000