spring:
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
    alicloud:
      sms:
        host: https://smsmsgs.market.alicloudapi.com
        path: /sms/
        skin: 1
        sign: 1
        appcode: 你自己的AppCode

  application:
    name: mall-third-party

server:
  port: 30000